[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["sneks*"]
namespaces = true

[tool.setuptools.dynamic]
version = {file = ["VERSION.txt"]}

[project]
name = "sneks"
dynamic = ["version"]
description = "Sneks"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "Apache Software License"}
authors = [
    {name = "Nathaniel Schaaf", email = "nathaniel.schaaf@gmail.com"}
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]
dependencies = [
    "aws-cdk-lib>=2.125",
    "aws-cdk.aws-cognito-identitypool-alpha",
    "aws-lambda-powertools[all]>=2.30.2",
    "boto3",
    "constructs>=10",
    "pydantic",
]

[project.scripts]
cdk-app = "sneks.infrastructure.app:main"
validate = "sneks.application.engine.validator.main:main"
run = "sneks.application.engine.engine.runner:main"
poster = "sneks.application.engine.gui.poster:main"

[project.optional-dependencies]
dev = [
    "black",
    "boto3-stubs-lite[essential]",
    "isort",
    "moto",
    "mypy",
    "pytest",
    "pytest-cov",
    "tox",
    "build",
    "twine",
]
gui = [
    "pygame>=2.5.2",
]
record = [
    "pygame>=2.5.2",
    "moviepy",
]

[tool.black]
extend-exclude = "src/webapp"

[tool.isort]
profile = "black"
known_first_party = "sneks"
skip_glob = ["src/webapp"]
